"""Post-train stage package (evaluation, export, onnx, registry)."""

from post_train.evaluate import (
    EvaluationCohort,
    EvaluationCohortConflictError,
    EvaluationGroupLeakageError,
    EvaluationRunConflictError,
    EvaluationRunManifest,
    InsufficientClassCoverageError,
    MlEvaluationError,
    build_candidate_golden_cohort,
    build_candidate_recent_cohort,
    calculate_candidate_cohort_metrics,
    check_group_contamination,
    compute_average_precision,
    compute_roc_auc,
    derive_cohort_identity,
    derive_evaluation_run_identity,
    evaluate_candidate_model,
    select_candidate_validation_threshold,
)
from post_train.export import (
    ModelPackageConflictError,
    ModelPackageIntegrityError,
    ModelPackageManifest,
    ModelPromotionRecord,
    ModelPromotionRejectionError,
    ModelRegistry,
    ModelRegistryError,
    ModelRuntimeManifest,
    ModelRuntimeValidationRecord,
    OnnxExportError,
    OnnxParityError,
    OnnxRuntimeExporter,
    RuntimeExporter,
    canonical_runtime_features,
    compute_file_sha256,
    derive_model_package_identity,
    derive_promotion_identity,
    derive_runtime_package_identity,
)

__all__ = [
    # Evaluate
    "select_candidate_validation_threshold",
    "compute_average_precision",
    "compute_roc_auc",
    "calculate_candidate_cohort_metrics",
    "MlEvaluationError",
    "EvaluationGroupLeakageError",
    "EvaluationCohortConflictError",
    "EvaluationRunConflictError",
    "InsufficientClassCoverageError",
    "EvaluationCohort",
    "derive_cohort_identity",
    "check_group_contamination",
    "build_candidate_golden_cohort",
    "build_candidate_recent_cohort",
    "EvaluationRunManifest",
    "derive_evaluation_run_identity",
    "evaluate_candidate_model",
    # Export / Registry / ONNX
    "ModelRegistryError",
    "ModelPackageIntegrityError",
    "ModelPackageConflictError",
    "ModelPromotionRejectionError",
    "ModelPackageManifest",
    "derive_model_package_identity",
    "ModelPromotionRecord",
    "derive_promotion_identity",
    "ModelRegistry",
    "OnnxExportError",
    "OnnxParityError",
    "ModelRuntimeManifest",
    "ModelRuntimeValidationRecord",
    "derive_runtime_package_identity",
    "compute_file_sha256",
    "canonical_runtime_features",
    "RuntimeExporter",
    "OnnxRuntimeExporter",
]
