/**
 * @file types.ts
 * @description Domain models, response payloads, and visual styling constants
 * for the Lineage Explorer workflow.
 *
 * Lineage Explorer tracks end-to-end data provenance across the medallion lakehouse:
 *   - Bronze: Raw telescope data (FITS) ingested directly from NASA MAST.
 *   - Silver: Calibrated, detrended Parquet artifacts generated by the Rust preprocessor.
 *   - Lineage: Immutable SHA-256 cryptographic commit proof linking Bronze + Processor -> Silver.
 *   - Gold: Verified analytical snapshots and dataset manifests ready for ML training.
 */

/**
 * Supported telescope data product classifications.
 */
export type ProductKind = 'lightcurve' | 'target-pixel';

/**
 * Filter stages for narrowing down provenance ledger rows.
 */
export type StageFilter = 'all' | 'bronze' | 'silver' | 'gold';

/**
 * Storage object metadata stored in MinIO/S3 lakehouse tiers.
 */
export type StorageObject = {
  /** S3 key / object path */
  key: string;
  /** Size in bytes */
  size_bytes: number;
  /** S3 ETag hash (represents storage object identity) */
  etag?: string;
  /** ISO-8601 timestamp of last modification */
  last_modified: string;
};

/**
 * Scientific Gold resolution evidence indicating whether a product
 * has been incorporated into an immutable training/research manifest.
 */
export type GoldLineageResolution = {
  source_product_id: string;
  silver_object_key?: string;
  status: 'EXTRACTED' | 'PENDING';
  snapshot_id?: string;
  datasets?: string[];
};

/**
 * Flat backend record returned from GET /api/v1/lineage/ledger.
 */
export type BackendLineageRecord = {
  identity: string;
  tic_id: string;
  sector?: number | null;
  product_kind: ProductKind;
  source_product_id: string;
  bronze: StorageObject;
  silver?: StorageObject;
  processor_version?: string;
  lineage_id?: string;
  lineage?: StorageObject;
  gold?: GoldLineageResolution;
};

/**
 * Aggregate object counts across storage tiers returned from backend ledger.
 */
export type LineageInventory = {
  bronze: number;
  silver: number;
  lineage: number;
  gold: number;
};

/**
 * Paginated API envelope returned by GET /api/v1/lineage/ledger.
 */
export type LineageLedgerResponse = {
  items: BackendLineageRecord[];
  inventory: LineageInventory;
  total: number;
  page: number;
  page_size: number;
};

/**
 * Frontend client representation of a lineage ledger row (camelCase mapped).
 */
export type LineageRecord = {
  identity: string;
  ticID: string;
  sector: number | null;
  productKind: ProductKind;
  sourceProductID: string;
  bronze: StorageObject;
  silver?: StorageObject;
  processorVersion?: string;
  lineageID?: string;
  lineage?: StorageObject;
  gold?: GoldLineageResolution;
};

/**
 * Display labels and abbreviations for product kinds.
 */
export const PRODUCT_CONFIG: Record<ProductKind, { label: string; shortLabel: string }> = {
  lightcurve: {
    label: 'Light curves',
    shortLabel: 'LC',
  },
  'target-pixel': {
    label: 'Target pixels',
    shortLabel: 'TPF',
  },
};

/**
 * Text labels assigned to each resolved lineage stage.
 */
export const STAGE_LABELS: Record<Exclude<StageFilter, 'all'>, string> = {
  bronze: 'BRONZE ONLY',
  silver: 'SILVER ARTIFACT',
  gold: 'GOLD VERIFIED',
};

/**
 * Tailwind badge styling classes assigned to each resolved lineage stage.
 */
export const STAGE_CLASSES: Record<Exclude<StageFilter, 'all'>, string> = {
  bronze: 'border-amber-500/35 bg-amber-500/10 text-amber-700 dark:text-amber-300',
  silver: 'border-sky-500/35 bg-sky-500/10 text-sky-700 dark:text-sky-300',
  gold: 'border-violet-500/35 bg-violet-500/10 text-violet-700 dark:text-violet-300',
};
